### PR TITLE
Development

### PR DESCRIPTION
**Pull request by barnabyalter**
@etgrieco Can you review the other changes being staged for merging to master to see if any are problematic? That is, other than the ones from the `feature/unhide_availlinks` branch

### CODE REVIEW

**Comment by etgrieco** [comment]
@barnabyalter looks good to me. I'm surprised I didn't merge these in yet. Thanks for asking, looks like no conflicts. You can go ahead and merge it all and deploy when it's ready.

**Comment by barnabyalter** [comment]
@etgrieco fyi the reason we're sitting on this is because UX advised not to change the options (i.e. by adding the availability links on brief results) during finals. we'll merge it after finals next week

**Comment by etgrieco** [comment]
@barnabyalter BHS and new features changes merged in -- leaving to you to merge to `master` when reviews are complete on monday.com

**Comment by etgrieco** [comment]
@barnabyalter what I did was merge 4956fab manually into master so that production/master divergence wouldn't continue and await review. Everything up to 4956fab was approved so I merged from there. I'm closing this PR and starting over from d61c1f0 to clean the history up

**Pull request closed without merging**
